package com.feurle.tg.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleImageAllPropertiesEquals(ArticleImage expected, ArticleImage actual) {
        assertArticleImageAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleImageAllUpdatablePropertiesEquals(ArticleImage expected, ArticleImage actual) {
        assertArticleImageUpdatableFieldsEquals(expected, actual);
        assertArticleImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleImageAutoGeneratedPropertiesEquals(ArticleImage expected, ArticleImage actual) {
        assertThat(actual)
            .as("Verify ArticleImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleImageUpdatableFieldsEquals(ArticleImage expected, ArticleImage actual) {
        assertThat(actual)
            .as("Verify ArticleImage relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image contenty type").isEqualTo(expected.getImageContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleImageUpdatableRelationshipsEquals(ArticleImage expected, ArticleImage actual) {
        // empty method
    }
}
